/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Detail: typeof import('./pages/detail.vue')['default']
    ExamsIng: typeof import('./pages/examsIng.vue')['default']
    Pages: typeof import('./pages/index.vue')['default']
    Peak: typeof import('./pages/peak.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
